# Generated by Django 6.1 on 2026-08-28

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.web.analysis.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("changes", "0001_initial"), ("organizations", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("pull_request_snapshot", "Pull-request snapshot"),
                            ("installation_lifecycle", "Installation lifecycle"),
                            ("repository_lifecycle", "Repository lifecycle"),
                        ],
                        max_length=32,
                    ),
                ),
                ("task_version", models.CharField(default="v1", max_length=32)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("available_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_code", models.CharField(blank=True, max_length=64)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("correlation_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_jobs",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={"ordering": ("available_at", "id")},
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "topic",
                    models.CharField(
                        default="releaseproof.analysis.process_job.v1", max_length=128
                    ),
                ),
                ("payload_version", models.CharField(default="v1", max_length=16)),
                (
                    "payload",
                    models.JSONField(validators=[apps.web.analysis.models.validate_outbox_payload]),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("available_at", models.DateTimeField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_event",
                        to="analysis.analysisjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("available_at", "id")},
        ),
        migrations.AddConstraint(
            model_name="analysisjob",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="analysis_job_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="analysis_job_attempts_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="analysis_outbox_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("topic", "releaseproof.analysis.process_job.v1")),
                name="analysis_outbox_topic_allowlisted",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="analysis_outbox_attempts_bounded",
            ),
        ),
    ]
