# Generated by Django 6.1 on 2026-09-01 13:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.web.organizations.models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostedLLMPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version", models.PositiveIntegerField()),
                ("schema_version", models.CharField(default="hosted-llm-policy-v1", max_length=64)),
                (
                    "routing_mode",
                    models.CharField(
                        choices=[
                            ("local_only", "local_only"),
                            ("hosted_redacted", "hosted_redacted"),
                            ("hosted_allowed", "hosted_allowed"),
                        ],
                        default="local_only",
                        max_length=32,
                    ),
                ),
                (
                    "allowed_providers",
                    models.JSONField(
                        default=list,
                        validators=[apps.web.organizations.models.validate_llm_provider_list],
                    ),
                ),
                (
                    "allowed_models",
                    models.JSONField(
                        default=list,
                        validators=[apps.web.organizations.models.validate_llm_model_list],
                    ),
                ),
                (
                    "allowed_content_classes",
                    models.JSONField(
                        default=list,
                        validators=[apps.web.organizations.models.validate_llm_content_classes],
                    ),
                ),
                (
                    "max_transmitted_bytes",
                    models.PositiveIntegerField(
                        default=32768,
                        validators=[
                            django.core.validators.MinValueValidator(256),
                            django.core.validators.MaxValueValidator(131072),
                        ],
                    ),
                ),
                (
                    "max_input_tokens",
                    models.PositiveIntegerField(
                        default=49152,
                        validators=[
                            django.core.validators.MinValueValidator(256),
                            django.core.validators.MaxValueValidator(262144),
                        ],
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        default=1024,
                        validators=[
                            django.core.validators.MinValueValidator(64),
                            django.core.validators.MaxValueValidator(8192),
                        ],
                    ),
                ),
                (
                    "max_cost_microusd",
                    models.PositiveIntegerField(
                        default=100000,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000000),
                        ],
                    ),
                ),
                (
                    "redaction_version",
                    models.CharField(default="deterministic-redaction-v1", max_length=64),
                ),
                (
                    "training_use_mode",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("not_used_for_training", "not_used_for_training"),
                            ("contract_reviewed", "contract_reviewed"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("terms_reviewed_on", models.DateField(blank=True, null=True)),
                (
                    "retention_mode",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("provider_standard", "provider_standard"),
                            ("custom_duration", "custom_duration"),
                            ("contractual_zero_retention", "contractual_zero_retention"),
                        ],
                        default="unknown",
                        max_length=40,
                    ),
                ),
                ("retention_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "allowed_regions",
                    models.JSONField(
                        default=list,
                        validators=[apps.web.organizations.models.validate_llm_regions],
                    ),
                ),
                ("response_storage_disabled", models.BooleanField(default=True)),
                (
                    "approved_by_role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("admin", "Admin")], max_length=16
                    ),
                ),
                (
                    "connect_timeout_seconds",
                    models.FloatField(
                        default=5.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(60.0),
                        ],
                    ),
                ),
                (
                    "read_timeout_seconds",
                    models.FloatField(
                        default=60.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(300.0),
                        ],
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "retry_backoff_seconds",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_llm_policies",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_llm_policies",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "repository_id", "version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "repository", "id"),
                        name="organizations_llm_policy_org_repo_id_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("repository__isnull", True)),
                        fields=("organization", "version"),
                        name="organizations_llm_policy_org_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("repository__isnull", False)),
                        fields=("repository", "version"),
                        name="organizations_llm_policy_repo_version_unique",
                    ),
                ],
            },
        ),
    ]
