# Generated by Django 6.1 on 2026-09-08 13:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.web.organizations.models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_llm_policy_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(
                        default="operational-policy-v1", editable=False, max_length=64
                    ),
                ),
                (
                    "quota_limits",
                    models.JSONField(
                        default=apps.web.organizations.models.default_operational_quota_limits,
                        validators=[
                            apps.web.organizations.models.validate_operational_quota_limits
                        ],
                    ),
                ),
                (
                    "retention_days",
                    models.JSONField(
                        default=apps.web.organizations.models.default_operational_retention_days,
                        validators=[
                            apps.web.organizations.models.validate_operational_retention_days
                        ],
                    ),
                ),
                ("policy_sha256", models.CharField(editable=False, max_length=64)),
                (
                    "approved_by_role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("admin", "Admin")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releaseproof_operational_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_policies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="RetentionDeletionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("dry_run", models.BooleanField(default=True)),
                ("cutoff_by_class", models.JSONField()),
                (
                    "candidate_public_ids",
                    models.JSONField(
                        validators=[apps.web.organizations.models.validate_retention_candidates]
                    ),
                ),
                ("plan_sha256", models.CharField(max_length=64)),
                ("correlation_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_deletion_plans",
                        to="organizations.organization",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_deletion_plans",
                        to="organizations.operationalpolicy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releaseproof_retention_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetentionDeletionGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_deletion_grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_grant",
                        to="organizations.retentiondeletionplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetentionDeletionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("deleted_counts", models.JSONField(default=dict)),
                ("blocked_counts", models.JSONField(default=dict)),
                ("result_sha256", models.CharField(max_length=64)),
                ("correlation_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releaseproof_retention_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_deletion_executions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution",
                        to="organizations.retentiondeletionplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scope", models.CharField(max_length=16)),
                ("subject_key", models.CharField(max_length=128)),
                ("quota_kind", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("window_ends_at", models.DateTimeField()),
                ("limit", models.PositiveBigIntegerField()),
                ("consumed", models.PositiveBigIntegerField(default=0)),
                ("policy_version", models.PositiveIntegerField()),
                ("policy_sha256", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releaseproof_usage_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_counters",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("scope", models.CharField(max_length=16)),
                ("subject_key", models.CharField(max_length=128)),
                ("quota_kind", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("quantity", models.PositiveBigIntegerField()),
                ("correlation_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releaseproof_usage_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="organizations.usagecounter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_reservations",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="operationalpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "version"),
                name="organizations_ops_policy_org_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "policy_sha256"),
                name="organizations_ops_policy_org_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentiondeletionplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "plan_sha256"),
                name="organizations_retention_plan_org_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="usagecounter",
            constraint=models.UniqueConstraint(
                fields=("organization", "scope", "subject_key", "quota_kind", "window_started_at"),
                name="organizations_usage_window_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="usagecounter",
            constraint=models.CheckConstraint(
                condition=models.Q(("consumed__lte", models.F("limit"))),
                name="organizations_usage_within_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="usagereservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "scope", "quota_kind", "idempotency_key"),
                name="organizations_usage_reservation_unique",
            ),
        ),
    ]
