# Generated by Django 6.1 on 2026-09-08 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_operationalpolicy_retentiondeletionplan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="operationalpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="organizations_ops_policy_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="retentiondeletionexecution",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="organizations_retention_execution_org_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentiondeletionplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="organizations_retention_plan_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="usagecounter",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="organizations_usage_counter_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="usagereservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="organizations_usage_reservation_org_id_unique"
            ),
        ),
    ]
