# Generated by Django 6.1 on 2026-08-28

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.web.repositories.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("github_installation_id", models.PositiveBigIntegerField(unique=True)),
                ("github_account_id", models.PositiveBigIntegerField()),
                (
                    "account_login",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="GitHub owner and repository names must use the bounded GitHub name subset",
                                regex="^[A-Za-z0-9_.-]{1,100}$",
                            )
                        ],
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        validators=[apps.web.repositories.models.validate_github_permissions],
                    ),
                ),
                (
                    "credential_reference",
                    models.CharField(
                        max_length=512,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="credential reference must name an approved secret source without containing a token",
                                regex="^(env|file|vault|aws-secretsmanager|gcp-secret-manager|azure-key-vault):[^\\s]{1,480}$",
                            )
                        ],
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("installed_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="github_installations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("organization_id", "id")},
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("github_repository_id", models.PositiveBigIntegerField(unique=True)),
                (
                    "owner",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="GitHub owner and repository names must use the bounded GitHub name subset",
                                regex="^[A-Za-z0-9_.-]{1,100}$",
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="GitHub owner and repository names must use the bounded GitHub name subset",
                                regex="^[A-Za-z0-9_.-]{1,100}$",
                            )
                        ],
                    ),
                ),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("primary_language", models.CharField(blank=True, max_length=64)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("analysis_enabled", models.BooleanField(default=True)),
                ("indexing_enabled", models.BooleanField(default=True)),
                ("execution_allowed", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repositories",
                        to="repositories.githubinstallation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repositories",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("organization_id", "owner", "name")},
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="repositories_installation_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubinstallation",
            constraint=models.UniqueConstraint(
                fields=("organization", "github_account_id"),
                name="repositories_installation_org_account_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="repositories_repository_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("organization", "owner", "name"),
                name="repositories_repository_org_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.CheckConstraint(
                condition=models.Q(("execution_allowed", False)),
                name="repositories_execution_disabled_before_m9",
            ),
        ),
    ]
