# Generated by Django 6.1 on 2026-08-28

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.web.changes.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations", "0001_initial"), ("repositories", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="WebhookReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "delivery_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[apps.web.changes.models.validate_delivery_id],
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_event_name]
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("payload_size", models.PositiveIntegerField()),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_receipts",
                        to="repositories.githubinstallation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_receipts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("-received_at", "-id")},
        ),
        migrations.CreateModel(
            name="PullRequestSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("pull_request_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField(blank=True)),
                ("base_ref", models.CharField(max_length=255)),
                ("head_ref", models.CharField(max_length=255)),
                (
                    "base_sha",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_sha]
                    ),
                ),
                (
                    "head_sha",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_sha]
                    ),
                ),
                (
                    "changed_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.web.changes.models.validate_changed_files],
                    ),
                ),
                (
                    "checks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.web.changes.models.validate_checks],
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="github-pr-snapshot-v1", editable=False, max_length=64
                    ),
                ),
                (
                    "snapshot_checksum",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[apps.web.changes.models.validate_checksum],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pull_request_snapshots",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pull_request_snapshots",
                        to="repositories.repository",
                    ),
                ),
                (
                    "first_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_snapshots",
                        to="changes.webhookreceipt",
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.AddConstraint(
            model_name="webhookreceipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="changes_receipt_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestsnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="changes_snapshot_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pullrequestsnapshot",
            constraint=models.UniqueConstraint(
                fields=(
                    "repository",
                    "pull_request_number",
                    "base_sha",
                    "head_sha",
                    "schema_version",
                ),
                name="changes_snapshot_identity_unique",
            ),
        ),
    ]
