# Generated by Django 6.1 on 2026-08-28 19:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.web.changes.models


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequestsnapshot",
            name="author_key",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[apps.web.changes.models.validate_author_key],
            ),
        ),
        migrations.AddField(
            model_name="pullrequestsnapshot",
            name="commit_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pullrequestsnapshot",
            name="schema_version",
            field=models.CharField(default="github-pr-snapshot-v2", editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name="ChangeFeatureSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("prediction_time", models.DateTimeField()),
                ("diff_schema_version", models.CharField(max_length=64)),
                (
                    "feature_schema_version",
                    models.CharField(default="change-features-v1", max_length=64),
                ),
                ("extractor_version", models.CharField(max_length=64)),
                ("graph_schema_version", models.CharField(max_length=64)),
                ("history_schema_version", models.CharField(max_length=64)),
                (
                    "evidence_schema_version",
                    models.CharField(default="deterministic-risk-factor-v1", max_length=64),
                ),
                (
                    "normalized_diff",
                    models.JSONField(
                        validators=[apps.web.changes.models.validate_versioned_object]
                    ),
                ),
                (
                    "diff_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "feature_values",
                    models.JSONField(validators=[apps.web.changes.models.validate_feature_values]),
                ),
                (
                    "feature_missing",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[apps.web.changes.models.validate_feature_metadata],
                    ),
                ),
                (
                    "feature_provenance",
                    models.JSONField(
                        validators=[apps.web.changes.models.validate_feature_provenance]
                    ),
                ),
                (
                    "feature_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "graph",
                    models.JSONField(
                        validators=[apps.web.changes.models.validate_versioned_object]
                    ),
                ),
                (
                    "graph_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "blast_radius",
                    models.JSONField(
                        validators=[apps.web.changes.models.validate_versioned_object]
                    ),
                ),
                (
                    "historical_statistics",
                    models.JSONField(
                        validators=[apps.web.changes.models.validate_versioned_object]
                    ),
                ),
                (
                    "result_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_feature_sets",
                        to="organizations.organization",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feature_sets",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="changes_features_org_id_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("snapshot", "feature_schema_version", "extractor_version"),
                        name="changes_features_snapshot_version_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("id", "snapshot"), name="changes_features_id_snapshot_unique"
                    ),
                ],
            },
        ),
    ]
