# Generated by Django 6.1 on 2026-08-28 19:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.web.evidence.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("changes", "0002_pullrequestsnapshot_author_key_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("ml", "Machine learning"),
                            ("retrieval", "Retrieval"),
                            ("llm", "LLM"),
                            ("test", "Test"),
                            ("execution", "Execution"),
                            ("security", "Security"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rule_id", models.CharField(max_length=160)),
                ("title", models.CharField(max_length=256)),
                ("value", models.JSONField(blank=True, null=True)),
                ("reason", models.CharField(max_length=512)),
                (
                    "source_refs",
                    models.JSONField(
                        default=list, validators=[apps.web.evidence.models.validate_source_refs]
                    ),
                ),
                ("missing", models.BooleanField(default=False)),
                ("producer_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="changes.changefeatureset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="organizations.organization",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("feature_set", "sequence"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="evidence_item_org_id_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("feature_set", "sequence"),
                        name="evidence_item_feature_sequence_unique",
                    ),
                ],
            },
        ),
    ]
