# Generated by Django 6.1 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("evidence", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="evidenceitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("deterministic", "Deterministic"),
                    ("ml", "Machine learning"),
                    ("retrieval", "Retrieval"),
                    ("llm", "LLM"),
                    ("agent", "Agent investigation"),
                    ("test", "Test"),
                    ("execution", "Execution"),
                    ("security", "Security"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
            ),
        )
    ]
