# Generated by Django 6.1 on 2026-08-31 14:33

import uuid

import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

import apps.web.changes.models
import packages.retrieval_core.contracts


def enable_vector_extension(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def keep_shared_vector_extension(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    del apps, schema_editor


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(enable_vector_extension, keep_shared_vector_extension),
        migrations.CreateModel(
            name="EmbeddingIndexProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version", models.CharField(max_length=96)),
                ("model_id", models.CharField(max_length=256)),
                ("model_revision", models.CharField(max_length=40)),
                (
                    "artifact_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("artifact_license", models.CharField(max_length=64)),
                ("dimension", models.PositiveSmallIntegerField(default=384)),
                ("adapter_version", models.CharField(max_length=64)),
                ("chunking_version", models.CharField(max_length=64)),
                (
                    "physical_table_name",
                    models.CharField(default="retrieval_knowledgeembedding384", max_length=96),
                ),
                (
                    "physical_index_name",
                    models.CharField(
                        default="retrieval_embedding384_cosine_hnsw_v1", max_length=96
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("building", "building"),
                            ("ready", "ready"),
                            ("active", "active"),
                            ("retired", "retired"),
                            ("failed", "failed"),
                        ],
                        default=packages.retrieval_core.contracts.IndexLifecycle["BUILDING"],
                        max_length=16,
                    ),
                ),
                ("build_error_code", models.CharField(blank=True, max_length=64)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embedding_index_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embedding_index_profiles",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "repository_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pr_summary", "pr_summary"),
                            ("adr", "adr"),
                            ("incident", "incident"),
                            ("postmortem", "postmortem"),
                            ("runbook", "runbook"),
                            ("documentation", "documentation"),
                            ("python_source", "python_source"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(max_length=512)),
                ("source_version", models.CharField(max_length=128)),
                ("source_uri", models.CharField(max_length=1200)),
                ("title", models.CharField(max_length=256)),
                ("content_text", models.TextField()),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("content_byte_count", models.PositiveIntegerField()),
                ("chunking_version", models.CharField(max_length=64)),
                ("retention_class", models.CharField(max_length=32)),
                ("retention_policy_version", models.CharField(max_length=64)),
                ("retain_until", models.DateTimeField()),
                ("approved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_documents",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "repository_id", "source_type", "source_id"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("heading", models.CharField(max_length=256)),
                ("content_text", models.TextField()),
                ("normalized_text", models.TextField()),
                (
                    "content_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("start_line", models.PositiveIntegerField()),
                ("end_line", models.PositiveIntegerField()),
                ("chunking_version", models.CharField(max_length=64)),
                ("normalizer_version", models.CharField(max_length=64)),
                ("strategy", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_chunks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_chunks",
                        to="repositories.repository",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="retrieval.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ("document_id", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEmbedding384",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("vector", pgvector.django.vector.VectorField(dimensions=384)),
                (
                    "vector_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embeddings_384",
                        to="retrieval.knowledgechunk",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_embeddings_384",
                        to="organizations.organization",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="retrieval.embeddingindexprofile",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_embeddings_384",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ("profile_id", "chunk_id"),
            },
        ),
        migrations.CreateModel(
            name="LexicalIndexProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version", models.CharField(max_length=64)),
                ("configuration", models.CharField(default="simple", max_length=32)),
                ("normalizer_version", models.CharField(max_length=64)),
                ("chunking_version", models.CharField(max_length=64)),
                (
                    "physical_index_name",
                    models.CharField(default="retrieval_lexical_search_gin_v1", max_length=96),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("building", "building"),
                            ("ready", "ready"),
                            ("active", "active"),
                            ("retired", "retired"),
                            ("failed", "failed"),
                        ],
                        default=packages.retrieval_core.contracts.IndexLifecycle["BUILDING"],
                        max_length=16,
                    ),
                ),
                ("build_error_code", models.CharField(blank=True, max_length=64)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lexical_index_profiles",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lexical_index_profiles",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "repository_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeLexicalIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("search_document", models.TextField()),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lexical_indexes",
                        to="retrieval.knowledgechunk",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_lexical_indexes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_lexical_indexes",
                        to="repositories.repository",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="retrieval.lexicalindexprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("profile_id", "chunk_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="embeddingindexprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "id"),
                name="retrieval_embedding_profile_org_repo_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingindexprofile",
            constraint=models.UniqueConstraint(
                fields=("repository", "version"),
                name="retrieval_embedding_profile_repo_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingindexprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("lifecycle", packages.retrieval_core.contracts.IndexLifecycle["ACTIVE"])
                ),
                fields=("organization", "repository"),
                name="retrieval_one_active_embedding_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingindexprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("dimension", 384)),
                name="retrieval_embedding_profile_dimension_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgedocument",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "id"),
                name="retrieval_document_org_repo_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgedocument",
            constraint=models.UniqueConstraint(
                fields=(
                    "repository",
                    "source_type",
                    "source_id",
                    "source_version",
                    "content_sha256",
                    "chunking_version",
                ),
                name="retrieval_document_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "id"),
                name="retrieval_chunk_org_repo_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunking_version", "sequence"),
                name="retrieval_chunk_document_version_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeembedding384",
            constraint=models.UniqueConstraint(
                fields=("profile", "chunk"), name="retrieval_embedding_profile_chunk_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="lexicalindexprofile",
            constraint=models.UniqueConstraint(
                fields=("organization", "repository", "id"),
                name="retrieval_lexical_profile_org_repo_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="lexicalindexprofile",
            constraint=models.UniqueConstraint(
                fields=("repository", "version"),
                name="retrieval_lexical_profile_repo_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="lexicalindexprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("lifecycle", packages.retrieval_core.contracts.IndexLifecycle["ACTIVE"])
                ),
                fields=("organization", "repository"),
                name="retrieval_one_active_lexical_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgelexicalindex",
            constraint=models.UniqueConstraint(
                fields=("profile", "chunk"), name="retrieval_lexical_profile_chunk_unique"
            ),
        ),
    ]
