# Generated by Django 6.1 on 2026-08-28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.web.audit.models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("action", models.CharField(max_length=128)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_public_id", models.UUIDField()),
                ("correlation_id", models.UUIDField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[apps.web.audit.models.validate_safe_metadata],
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releaseproof_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("-occurred_at", "-id")},
        )
    ]
