# Generated by Django 6.1 on 2026-08-30 18:29

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.web.changes.models
import apps.web.risk.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("changes", "0002_pullrequestsnapshot_author_key_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("schema_version", models.CharField(max_length=64)),
                ("artifact_version", models.CharField(max_length=64)),
                (
                    "artifact_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("feature_schema_version", models.CharField(max_length=64)),
                ("threshold_policy_version", models.CharField(max_length=64)),
                ("threshold", models.PositiveSmallIntegerField()),
                ("raw_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("calibrated_probability", models.FloatField(blank=True, null=True)),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("proxy_prediction", models.BooleanField(blank=True, null=True)),
                (
                    "contributions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.web.risk.models.validate_contributions],
                    ),
                ),
                (
                    "missing_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.web.risk.models.validate_missing_required],
                    ),
                ),
                (
                    "result_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_scores",
                        to="changes.changefeatureset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_scores",
                        to="organizations.organization",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_scores",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="risk_score_org_id_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("id", "snapshot"), name="risk_score_id_snapshot_unique"
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "feature_set",
                            "artifact_version",
                            "artifact_hash",
                            "threshold_policy_version",
                        ),
                        name="risk_score_feature_artifact_unique",
                    ),
                ],
            },
        ),
    ]
