# Generated by Django 6.1 on 2026-09-07 14:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.web.changes.models
import apps.web.risk.models


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0002_pullrequestsnapshot_author_key_and_more"),
        ("organizations", "0003_llm_policy_integrity"),
        ("repositories", "0001_initial"),
        ("risk", "0002_tenant_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernedModelArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="governed-model-artifact-v1", max_length=64),
                ),
                ("model_name", models.CharField(max_length=128)),
                ("artifact_version", models.CharField(max_length=128)),
                (
                    "artifact_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("artifact_uri", models.CharField(max_length=1024)),
                ("algorithm", models.CharField(max_length=128)),
                (
                    "formal_experiment_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("mlflow_run_id", models.CharField(max_length=64)),
                ("dataset_version", models.CharField(max_length=128)),
                (
                    "dataset_manifest_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("feature_schema_version", models.CharField(max_length=128)),
                (
                    "input_schema_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "runtime_compatibility",
                    models.JSONField(
                        validators=[apps.web.risk.models.validate_safe_string_mapping]
                    ),
                ),
                ("synthetic", models.BooleanField(default=False)),
                ("contains_customer_data", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governed_model_artifacts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governed_model_artifacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "model_name", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="DriftAssessmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="data-quality-drift-assessment-v1", max_length=64),
                ),
                (
                    "policy_version",
                    models.CharField(default="data-quality-drift-policy-v1", max_length=64),
                ),
                (
                    "reference_profile_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "current_profile_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pass", "pass"),
                            ("review", "review"),
                            ("insufficient_data", "insufficient_data"),
                            ("incompatible_schema", "incompatible_schema"),
                        ],
                        max_length=32,
                    ),
                ),
                ("row_count", models.PositiveIntegerField()),
                (
                    "report",
                    models.JSONField(validators=[apps.web.risk.models.validate_drift_report]),
                ),
                (
                    "assessment_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("human_review_required", models.BooleanField()),
                (
                    "automatic_retraining_allowed",
                    models.BooleanField(default=False, editable=False),
                ),
                ("automatic_promotion_allowed", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drift_assessments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drift_assessments",
                        to="risk.governedmodelartifact",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ModelDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_name", models.CharField(max_length=128)),
                ("generation", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_deployments",
                        to="risk.governedmodelartifact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_deployments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "rollback_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_deployments",
                        to="risk.governedmodelartifact",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "model_name"),
            },
        ),
        migrations.CreateModel(
            name="ModelLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                ("policy_version", models.CharField(default="model-lifecycle-v1", max_length=64)),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("candidate", "candidate"),
                            ("staging", "staging"),
                            ("active", "active"),
                            ("retired", "retired"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("candidate", "candidate"),
                            ("staging", "staging"),
                            ("active", "active"),
                            ("retired", "retired"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("register", "register"),
                            ("promote_to_staging", "promote_to_staging"),
                            ("activate", "activate"),
                            ("retire", "retire"),
                            ("rollback", "rollback"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "evaluation_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[apps.web.changes.models.validate_checksum],
                    ),
                ),
                ("compatibility", models.JSONField(blank=True, default=dict)),
                (
                    "compatibility_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[apps.web.changes.models.validate_checksum],
                    ),
                ),
                (
                    "reviewer_role",
                    models.CharField(
                        blank=True,
                        choices=[("owner", "Owner"), ("admin", "Admin")],
                        max_length=16,
                    ),
                ),
                (
                    "approval_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[apps.web.changes.models.validate_checksum],
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                (
                    "event_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="risk.governedmodelartifact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_lifecycle_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("artifact_id", "sequence", "id"),
            },
        ),
        migrations.CreateModel(
            name="DeploymentOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="deployment-outcome-v1", max_length=64),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("no_issue", "no_issue"),
                            ("revert", "revert"),
                            ("hotfix", "hotfix"),
                            ("incident", "incident"),
                            ("manual_label", "manual_label"),
                            ("unknown", "unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("deployment_system", "deployment_system"),
                            ("incident_system", "incident_system"),
                            ("manual_review", "manual_review"),
                            ("repository_event", "repository_event"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_event_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("provenance_known", models.BooleanField(default=False)),
                ("explicit_learning_opt_in", models.BooleanField(default=False)),
                (
                    "organization_learning_enabled_at_ingest",
                    models.BooleanField(default=False),
                ),
                ("organization_policy_version", models.PositiveIntegerField()),
                ("observation_window_started_at", models.DateTimeField()),
                ("observation_window_ended_at", models.DateTimeField()),
                ("signal_observed_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField()),
                ("organization_training_eligible", models.BooleanField(default=False)),
                ("shared_training_eligible", models.BooleanField(default=False, editable=False)),
                ("eligibility_reason", models.CharField(max_length=128)),
                (
                    "record_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_outcomes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_outcomes",
                        to="risk.riskscore",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_outcomes",
                        to="repositories.repository",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_outcomes",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="risk_outcome_org_id_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "source_event_sha256"),
                        name="risk_outcome_org_source_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("shared_training_eligible", False)),
                        name="risk_outcome_never_shared_training",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", "deployment-outcome-v1")),
                        name="risk_outcome_schema_v1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DriftReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("no_action", "No action"),
                            ("investigate", "Investigate"),
                            ("approve_experiment", "Approve retraining experiment only"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drift_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="risk.driftassessmentrecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drift_reviews",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="risk_drift_review_org_id_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="governedmodelartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="risk_model_artifact_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="governedmodelartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "model_name", "artifact_version"),
                name="risk_model_artifact_org_name_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="governedmodelartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "model_name", "artifact_sha256"),
                name="risk_model_artifact_org_name_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="governedmodelartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "model_name", "id"),
                name="risk_model_artifact_org_name_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="governedmodelartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "governed-model-artifact-v1")),
                name="risk_model_artifact_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="driftassessmentrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="risk_drift_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="driftassessmentrecord",
            constraint=models.UniqueConstraint(
                fields=("artifact", "current_profile_sha256", "policy_version"),
                name="risk_drift_artifact_profile_policy_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="driftassessmentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("automatic_retraining_allowed", False)),
                name="risk_drift_no_automatic_retraining",
            ),
        ),
        migrations.AddConstraint(
            model_name="driftassessmentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("automatic_promotion_allowed", False)),
                name="risk_drift_no_automatic_promotion",
            ),
        ),
        migrations.AddConstraint(
            model_name="modeldeployment",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="risk_model_deployment_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="modeldeployment",
            constraint=models.UniqueConstraint(
                fields=("organization", "model_name"), name="risk_model_deployment_org_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="modellifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="risk_model_event_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="modellifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("artifact", "sequence"), name="risk_model_event_artifact_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="modellifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("artifact", "event_sha256"), name="risk_model_event_artifact_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="modellifecycleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_version", "model-lifecycle-v1")),
                name="risk_model_event_policy_v1",
            ),
        ),
    ]
