# Generated by Django 6.1 on 2026-09-01 14:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.web.changes.models
import apps.web.verification.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evidence", "0001_initial"),
        ("organizations", "0003_llm_policy_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedTestProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("proposal_group_id", models.UUIDField(default=uuid.uuid4)),
                ("revision", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(default="generated-test-proposal-v1", max_length=64),
                ),
                (
                    "proposal_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("target_behavior", models.CharField(max_length=500)),
                ("rationale", models.TextField(max_length=2000)),
                (
                    "evidence_ids",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_proposal_evidence_ids]
                    ),
                ),
                ("file_path", models.CharField(max_length=240)),
                ("patch", models.TextField(max_length=65536)),
                (
                    "commands",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_proposal_commands]
                    ),
                ),
                ("expected_result", models.TextField(max_length=1000)),
                (
                    "risk",
                    models.CharField(
                        choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                        max_length=16,
                    ),
                ),
                ("test_adapter", models.CharField(max_length=64)),
                ("test_adapter_version", models.CharField(max_length=64)),
                (
                    "generation_metadata",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_generation_metadata]
                    ),
                ),
                (
                    "validation_report",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_static_validation_report]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_test_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_test_proposals",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="verification.generatedtestproposal",
                    ),
                ),
                (
                    "source_llm_evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_test_proposals",
                        to="evidence.evidenceitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProposalLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "from_lifecycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("accepted_for_export", "Accepted for export"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "to_lifecycle",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("accepted_for_export", "Accepted for export"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason_code", models.CharField(max_length=128)),
                ("correlation_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_lifecycle_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="verification.generatedtestproposal",
                    ),
                ),
            ],
            options={
                "ordering": ("proposal_id", "sequence", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="generatedtestproposal",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_proposal_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedtestproposal",
            constraint=models.UniqueConstraint(
                fields=("proposal_group_id", "revision"),
                name="verification_proposal_group_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedtestproposal",
            constraint=models.UniqueConstraint(
                fields=("source_llm_evidence", "proposal_hash"),
                name="verification_proposal_source_hash_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposallifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_event_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposallifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("proposal", "sequence"), name="verification_event_proposal_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposallifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("proposal", "to_lifecycle"),
                name="verification_event_proposal_lifecycle_unique",
            ),
        ),
    ]
