# Generated by Django 6.1 on 2026-09-01 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0001_initial"),
        ("organizations", "0003_llm_policy_integrity"),
        ("verification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="generatedtestproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "generated-test-proposal-v1")),
                name="verification_proposal_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedtestproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("risk__in", ["low", "medium", "high"])),
                name="verification_proposal_risk_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposallifecycleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("to_lifecycle__in", ["draft", "accepted_for_export", "rejected", "superseded"])
                ),
                name="verification_event_to_lifecycle_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposallifecycleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_lifecycle__isnull", True),
                    (
                        "from_lifecycle__in",
                        ["draft", "accepted_for_export", "rejected", "superseded"],
                    ),
                    _connector="OR",
                ),
                name="verification_event_from_lifecycle_allowed",
            ),
        ),
    ]
