# Generated by Django 6.1 on 2026-09-02 01:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.web.changes.models
import apps.web.verification.models


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0002_pullrequestsnapshot_author_key_and_more"),
        ("organizations", "0003_llm_policy_integrity"),
        ("verification", "0003_tenant_lifecycle_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="releaseproof.execution-plan.v1", max_length=64),
                ),
                (
                    "plan_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "proposal_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "snapshot_head_sha",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_sha]
                    ),
                ),
                ("image", models.CharField(max_length=160)),
                (
                    "fixture_tree_sha256",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_execution_plan_payload]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_plans",
                        to="organizations.organization",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_plans",
                        to="verification.generatedtestproposal",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_plans",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ExecutionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "snapshot_head_sha",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_sha]
                    ),
                ),
                (
                    "proposal_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "plan_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("correlation_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_approvals",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval",
                        to="verification.executionplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="releaseproof.execution-result.v1", max_length=64),
                ),
                (
                    "result_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("passed", "passed"),
                            ("failed", "failed"),
                            ("timeout", "timeout"),
                            ("killed", "killed"),
                            ("isolation_failure", "isolation_failure"),
                            ("runner_unavailable", "runner_unavailable"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("stale_at_recording", models.BooleanField(default=False)),
                (
                    "payload",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_execution_result_payload]
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="verification.executionapproval",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_runs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="verification.executionplan",
                    ),
                ),
            ],
            options={
                "ordering": ("plan_id", "attempt", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="executionplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_plan_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "plan_hash"), name="verification_plan_org_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "releaseproof.execution-plan.v1")),
                name="verification_execution_plan_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionapproval",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_approval_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_run_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="verification_run_org_idempotent"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.UniqueConstraint(
                fields=("plan", "attempt"), name="verification_run_plan_attempt_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "releaseproof.execution-result.v1")),
                name="verification_execution_result_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "passed",
                            "failed",
                            "timeout",
                            "killed",
                            "isolation_failure",
                            "runner_unavailable",
                        ],
                    )
                ),
                name="verification_execution_outcome_allowed",
            ),
        ),
    ]
