# Generated by Django 6.1 on 2026-09-02 14:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.web.changes.models
import apps.web.verification.models


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0002_pullrequestsnapshot_author_key_and_more"),
        ("organizations", "0003_llm_policy_integrity"),
        ("verification", "0005_execution_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DifferentialPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="releaseproof.differential-plan.v1", max_length=64),
                ),
                (
                    "plan_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "base_sha",
                    models.CharField(
                        max_length=40, validators=[apps.web.changes.models.validate_sha]
                    ),
                ),
                (
                    "candidate_sha",
                    models.CharField(
                        max_length=40, validators=[apps.web.changes.models.validate_sha]
                    ),
                ),
                ("image", models.CharField(max_length=160)),
                (
                    "payload",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_differential_plan_payload]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="differential_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="differential_plans",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="differential_plans",
                        to="verification.executionapproval",
                    ),
                ),
                (
                    "source_execution_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="differential_plan",
                        to="verification.executionplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="DifferentialRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "schema_version",
                    models.CharField(default="releaseproof.differential-result.v1", max_length=64),
                ),
                (
                    "result_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("no_difference", "no_difference"),
                            ("difference", "difference"),
                            ("base_failed", "base_failed"),
                            ("unknown", "unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("mutation_killed", models.PositiveSmallIntegerField()),
                ("mutation_total", models.PositiveSmallIntegerField()),
                ("idempotency_key", models.UUIDField()),
                ("stale_at_recording", models.BooleanField(default=False)),
                (
                    "payload",
                    models.JSONField(
                        validators=[
                            apps.web.verification.models.validate_differential_result_payload
                        ]
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="differential_runs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="verification.differentialplan",
                    ),
                ),
            ],
            options={
                "ordering": ("plan_id", "attempt", "id"),
            },
        ),
        migrations.CreateModel(
            name="RecommendationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "policy_version",
                    models.CharField(default="recommendation-fusion-v1", max_length=64),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("SHIP", "SHIP"),
                            ("REVIEW", "REVIEW"),
                            ("HOLD", "HOLD"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "inputs_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "decision_hash",
                    models.CharField(
                        max_length=64, validators=[apps.web.changes.models.validate_checksum]
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        validators=[apps.web.verification.models.validate_recommendation_payload]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_decisions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "differential_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_decisions",
                        to="verification.differentialrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_decisions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation_decisions",
                        to="changes.pullrequestsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="differentialplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_diff_plan_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialplan",
            constraint=models.UniqueConstraint(
                fields=("organization", "plan_hash"), name="verification_diff_plan_org_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "releaseproof.differential-plan.v1")),
                name="verification_diff_plan_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_diff_run_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="verification_diff_run_org_idempotent",
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrun",
            constraint=models.UniqueConstraint(
                fields=("plan", "attempt"), name="verification_diff_run_plan_attempt_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "releaseproof.differential-result.v1")),
                name="verification_diff_result_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outcome__in", ["no_difference", "difference", "base_failed", "unknown"])
                ),
                name="verification_diff_outcome_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="differentialrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("mutation_killed__lte", models.F("mutation_total"))),
                name="verification_mutation_killed_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationdecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="verification_rec_org_id_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationdecision",
            constraint=models.UniqueConstraint(
                fields=("differential_run", "policy_version"),
                name="verification_rec_run_policy_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_version", "recommendation-fusion-v1")),
                name="verification_rec_policy_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("recommendation__in", ["SHIP", "REVIEW", "HOLD", "UNKNOWN"])),
                name="verification_rec_value_allowed",
            ),
        ),
    ]
